const BookActionTypes = {
    FETCH_BOOK_BY_ID_START: "FETCH_BOOK_BY_ID_START",
    FETCH_BOOK_BY_ID_SUCCESS: "FETCH_BOOK_BY_ID_SUCCESS",
    FETCH_BOOK_BY_ID_FAILURE: "FETCH_BOOK_BY_ID_FAILURE",

    FETCH_BOOKS_BY_GENRES_START: "FETCH_BOOKS_BY_GENRES_START",
    FETCH_BOOKS_BY_GENRES_SUCCESS: "FETCH_BOOKS_BY_GENRES_SUCCESS",
    FETCH_BOOKS_BY_GENRES_FAILURE: "FETCH_BOOKS_BY_GENRES_FAILURE",

    BOOK_LOAN_START: "BOOK_LOAN_START",
    BOOK_LOAN_SUCCESS: "BOOK_LOAN_SUCCESS",
    BOOK_LOAN_FAILURE: "BOOK_LOAN_FAILURE",

    LOAN_BOOKS: "LOAN_BOOKS",
};

export default BookActionTypes;
