const BookActionTypes = {
	FETCH_BOOK_BY_ID_START: "FETCH_BOOK_BY_ID_START",
	FETCH_BOOK_BY_ID_SUCCESS: "FETCH_BOOK_BY_ID_SUCCESS",
	FETCH_BOOK_BY_ID_FAILURE: "FETCH_BOOK_BY_ID_FAILURE",

	FETCH_BOOKS_BY_GENRES_START: "FETCH_BOOKS_BY_GENRES_START",
	FETCH_BOOKS_BY_GENRES_SUCCESS: "FETCH_BOOKS_BY_GENRES_SUCCESS",
	FETCH_BOOKS_BY_GENRES_FAILURE: "FETCH_BOOKS_BY_GENRES_FAILURE",

	FETCH_ALL_BOOK_START: "FETCH_ALL_BOOKS_START",
	FETCH_ALL_BOOK_SUCCESS: "FETCH_ALL_BOOKS_SUCCESS",
	FETCH_ALL_BOOK_FAILURE: "FETCH_ALL_BOOKS_FAILURE",

	BOOK_LOAN_START: "BOOK_LOAN_START",
	BOOK_LOAN_SUCCESS: "BOOK_LOAN_SUCCESS",
	BOOK_LOAN_FAILURE: "BOOK_LOAN_FAILURE",

	ADD_NEW_BOOK_START: "ADD_NEW_BOOK_START",
	ADD_NEW_BOOK_SUCCESS: "ADD_NEW_BOOK_SUCCESS",
	ADD_NEW_BOOK_FAILURE: "ADD_NEW_BOOK_FAILURE",

	ADD_EXISTENT_BOOK_START: "ADD_EXISTENT_BOOK_START",
	ADD_EXISTENT_BOOK_SUCCESS: "ADD_EXISTENT_BOOK_SUCCESS",
	ADD_EXISTENT_BOOK_FAILURE: "ADD_EXISTENT_BOOK_FAILURE",

	UPDATE_BOOKS: "UPDATE_BOOKS",

	LOAN_BOOKS: "LOAN_BOOKS",
};

export default BookActionTypes;
