const GenreActionTypes = {
	SET_GENRES: "SET_GENRES",

	FETCH_GENRES_START: "FETCH_GENRES_START",
	FETCH_GENRES_SUCCESS: "FETCH_GENRES_SUCCESS",
	FETCH_GENRES_FAILURE: "FETCH_GENRES_FAILURE",

	ADD_GENRE_START: "ADD_GENRE_START",
	ADD_GENRE_SUCCESS: "ADD_GENRE_SUCCESS",
	ADD_GENRE_FAILURE: "ADD_GENRE_FAILURE",

	UPDATE_GENRES: "UPDATE_GENRES",
};

export default GenreActionTypes;
