const GenreActionTypes = {
	SET_GENRES: "SET_GENRES",

	FETCH_GENRES_START: "FETCH_GENRES_START",
	FETCH_GENRES_SUCCESS: "FETCH_GENRES_SUCCESS",
	FETCH_GENRES_FAILURE: "FETCH_GENRES_FAILURE",
};

export default GenreActionTypes;
