const UserActionTypes = {
	SIGN_UP_USER_START: "SIGN_UP_USER_START",
	SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
	SIGN_UP_USER_FAILURE: "SIGN_UP_USER_FAILURE",

	EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN__START",
	GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",

	SIGN_IN_USER_SUCCESS: "SIGN_IN_USER_SUCCESS",
	SIGN_IN_USER_FAILURE: "SIGN_IN_USER_FAILURE",

	SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
	SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
	SIGN_OUT_USER_FAILURE: "SIGN_OUT_USER_FAILURE",

	CHECK_USER_SESSION: "CHECK_USER_SESSION",

	TOGGLE_USER_DROPDOWN_HIDDEN: "TOGGLE_USER_DROPDOWN_HIDDEN",
};

export default UserActionTypes;
