const UserActionTypes = {
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    TOGGLE_USER_DROPDOWN_HIDDEN: "TOGGLE_USER_DROPDOWN_HIDDEN",
    ADD_BOOKS: "ADD_BOOKS"
};

export default UserActionTypes;
